<?php
$file_path = 'c:\xampp\htdocs\sinalhan-hc-system\app\Views\patients\show.php';
$content = file_get_contents($file_path);
$content = str_replace("\r\n", "\n", $content);

// 1. PCB service logs variable
$old_pcb_var = "                                                        <?php \n                                                            \$canManagePcb = is_admin() || ((int)(\$_SESSION['user_id'] ?? 0) === (int)(\$log['recorded_by'] ?? 0));\n                                                        ?>";
$new_pcb_var = "                                                        <?php \n                                                            \$canDeletePcb = is_admin();\n                                                        ?>";
$content = str_replace($old_pcb_var, $new_pcb_var, $content);

// PCB buttons
$old_pcb_btn = "                                                            <?php if (\$canManagePcb): ?>\n                                                                <button type=\"button\" class=\"btn btn-sm btn-outline-secondary border-0 p-1 btn-edit-pcb-service\"\n                                                                    data-id=\"<?= \$log['id'] ?>\"\n                                                                    data-date=\"<?= h(\$log['service_date']) ?>\"\n                                                                    data-category=\"<?= h(\$log['service_category']) ?>\"\n                                                                    data-type=\"<?= h(\$log['service_type']) ?>\"\n                                                                    data-diagnosis=\"<?= h(\$log['diagnosis'] ?? '') ?>\"\n                                                                    data-given=\"<?= !empty(\$log['status_given']) ? '1' : '0' ?>\"\n                                                                    data-referred=\"<?= !empty(\$log['status_referred']) ? '1' : '0' ?>\"\n                                                                    data-referred-to=\"<?= h(\$log['referred_to'] ?? '') ?>\"\n                                                                    data-remarks=\"<?= h(\$log['remarks'] ?? '') ?>\"\n                                                                    title=\"Edit Encounter\">\n                                                                    <i class=\"bi bi-pencil-square fs-6\"></i>\n                                                                </button>\n                                                                <form action=\"<?= url('/pcb/service-log/' . \$log['id'] . '/delete') ?>\" method=\"POST\" class=\"d-inline\" onsubmit=\"return confirm('Are you sure you want to delete this <?= h(\$log['service_type']) ?> encounter record?');\">\n                                                                    <?= csrf_field() ?>\n                                                                    <button type=\"submit\" class=\"btn btn-sm btn-outline-danger border-0 p-1\" title=\"Delete Entry\">\n                                                                        <i class=\"bi bi-trash fs-6\"></i>\n                                                                    </button>\n                                                                </form>\n                                                            <?php endif; ?>";

$new_pcb_btn = "                                                                <button type=\"button\" class=\"btn btn-sm btn-outline-secondary border-0 p-1 btn-edit-pcb-service\"\n                                                                    data-id=\"<?= \$log['id'] ?>\"\n                                                                    data-date=\"<?= h(\$log['service_date']) ?>\"\n                                                                    data-category=\"<?= h(\$log['service_category']) ?>\"\n                                                                    data-type=\"<?= h(\$log['service_type']) ?>\"\n                                                                    data-diagnosis=\"<?= h(\$log['diagnosis'] ?? '') ?>\"\n                                                                    data-given=\"<?= !empty(\$log['status_given']) ? '1' : '0' ?>\"\n                                                                    data-referred=\"<?= !empty(\$log['status_referred']) ? '1' : '0' ?>\"\n                                                                    data-referred-to=\"<?= h(\$log['referred_to'] ?? '') ?>\"\n                                                                    data-remarks=\"<?= h(\$log['remarks'] ?? '') ?>\"\n                                                                    title=\"Edit Encounter\">\n                                                                    <i class=\"bi bi-pencil-square fs-6\"></i>\n                                                                </button>\n                                                            <?php if (\$canDeletePcb): ?>\n                                                                <form action=\"<?= url('/pcb/service-log/' . \$log['id'] . '/delete') ?>\" method=\"POST\" class=\"d-inline\" onsubmit=\"return confirm('Are you sure you want to delete this <?= h(\$log['service_type']) ?> encounter record?');\">\n                                                                    <?= csrf_field() ?>\n                                                                    <button type=\"submit\" class=\"btn btn-sm btn-outline-danger border-0 p-1\" title=\"Delete Entry\">\n                                                                        <i class=\"bi bi-trash fs-6\"></i>\n                                                                    </button>\n                                                                </form>\n                                                            <?php endif; ?>";
$content = str_replace($old_pcb_btn, $new_pcb_btn, $content);

// Consultations
$old_cons = "                                        <?php foreach (\$consultationsHistory as \$c): \n                                            \$canArchiveConsultation = is_admin() || \$curUserId === (int)(\$c['created_by'] ?? 0) || \$curUserId === (int)(\$c['consulted_by'] ?? 0);\n                                            \$canEditRow = \$canArchiveConsultation && (\$c['status'] !== 'Cancelled');";

$new_cons = "                                        <?php foreach (\$consultationsHistory as \$c): \n                                            \$canArchiveConsultation = is_admin();\n                                            \$canEditRow = (\$c['status'] !== 'Cancelled');";
$content = str_replace($old_cons, $new_cons, $content);

// Vitals var
$old_vital_var = "                                        <?php foreach (\$vitalsHistory as \$v): \n                                            \$canManageVital = is_admin() || \$curUserId === (int)(\$v['recorded_by'] ?? 0);\n                                        ?>";
$new_vital_var = "                                        <?php foreach (\$vitalsHistory as \$v): \n                                            \$canDeleteVital = is_admin();\n                                        ?>";
$content = str_replace($old_vital_var, $new_vital_var, $content);

// Vitals btn
$old_vital_btn = "                                                        <?php if (\$canManageVital): ?>\n                                                            <button type=\"button\" class=\"btn btn-sm btn-outline-secondary border-0 p-1 btn-edit-vitals\"\n                                                                data-id=\"<?= \$v['id'] ?>\"\n                                                                data-bp-systolic=\"<?= h(\$v['bp_systolic'] ?? '') ?>\"\n                                                                data-bp-diastolic=\"<?= h(\$v['bp_diastolic'] ?? '') ?>\"\n                                                                data-pulse=\"<?= h(\$v['heart_rate'] ?? '') ?>\"\n                                                                data-temp=\"<?= h(\$v['temperature'] ?? '') ?>\"\n                                                                data-resp=\"<?= h(\$v['respiratory_rate'] ?? '') ?>\"\n                                                                data-spo2=\"<?= h(\$v['oxygen_saturation'] ?? '') ?>\"\n                                                                data-weight=\"<?= h(\$v['weight'] ?? '') ?>\"\n                                                                data-height=\"<?= h(\$v['height'] ?? '') ?>\"\n                                                                data-waist=\"<?= h(\$v['waist_circumference'] ?? '') ?>\"\n                                                                data-notes=\"<?= h(\$v['notes'] ?? '') ?>\"\n                                                                title=\"Edit Vital Signs\">\n                                                                <i class=\"bi bi-pencil-square fs-6\"></i>\n                                                            </button>\n                                                            <button type=\"button\" class=\"btn btn-sm btn-outline-danger border-0 p-1 btn-delete-vital\" data-id=\"<?= \$v['id'] ?>\" title=\"Delete Vital Signs\">\n                                                                <i class=\"bi bi-trash fs-6\"></i>\n                                                            </button>\n                                                        <?php endif; ?>";

$new_vital_btn = "                                                            <button type=\"button\" class=\"btn btn-sm btn-outline-secondary border-0 p-1 btn-edit-vitals\"\n                                                                data-id=\"<?= \$v['id'] ?>\"\n                                                                data-bp-systolic=\"<?= h(\$v['bp_systolic'] ?? '') ?>\"\n                                                                data-bp-diastolic=\"<?= h(\$v['bp_diastolic'] ?? '') ?>\"\n                                                                data-pulse=\"<?= h(\$v['heart_rate'] ?? '') ?>\"\n                                                                data-temp=\"<?= h(\$v['temperature'] ?? '') ?>\"\n                                                                data-resp=\"<?= h(\$v['respiratory_rate'] ?? '') ?>\"\n                                                                data-spo2=\"<?= h(\$v['oxygen_saturation'] ?? '') ?>\"\n                                                                data-weight=\"<?= h(\$v['weight'] ?? '') ?>\"\n                                                                data-height=\"<?= h(\$v['height'] ?? '') ?>\"\n                                                                data-waist=\"<?= h(\$v['waist_circumference'] ?? '') ?>\"\n                                                                data-notes=\"<?= h(\$v['notes'] ?? '') ?>\"\n                                                                title=\"Edit Vital Signs\">\n                                                                <i class=\"bi bi-pencil-square fs-6\"></i>\n                                                            </button>\n                                                        <?php if (\$canDeleteVital): ?>\n                                                            <button type=\"button\" class=\"btn btn-sm btn-outline-danger border-0 p-1 btn-delete-vital\" data-id=\"<?= \$v['id'] ?>\" title=\"Delete Vital Signs\">\n                                                                <i class=\"bi bi-trash fs-6\"></i>\n                                                            </button>\n                                                        <?php endif; ?>";
$content = str_replace($old_vital_btn, $new_vital_btn, $content);

// Imm var
$old_imm_var = "                                        <?php foreach (\$patientImmunizations as \$imm): \n                                            \$canDeleteImm = is_admin() || \$curUserId === (int)(\$imm['administered_by'] ?? 0);\n                                        ?>";
$new_imm_var = "                                        <?php foreach (\$patientImmunizations as \$imm): \n                                            \$canDeleteImm = is_admin();\n                                        ?>";
$content = str_replace($old_imm_var, $new_imm_var, $content);

file_put_contents($file_path, $content);
echo "Done!\n";
